- hosts: localhost
  gather_facts: no
  become: yes
  vars:
    wg_ip: "{{ wgIp }}"
    wg_mask: "{{ wgMask }}"
    listen_port: {{ listenPort }}
    wgname: wg0
    config_dir: /etc/wireguard
  tasks:
    - name: Create a wireguard config directory if it does not exist
      ansible.builtin.file:
        path: {{ config_dir }}
        state: directory
        mode: '0600'

    - name: Generate server keys
      shell:
        cmd: wg genkey | tee privatekey | wg pubkey > publickey
        chdir: "{{ config_dir }}"

    - name: Read server privatekey and register into variable
      shell: cat {{ config_dir }}/privatekey
      register: privatekey

    - name: Read server publickey and register into variable
      shell: cat {{ config_dir }}/publickey
      register: publickey

    - name: Add {{ client_name }} to the server
      blockinfile:
        path: '{{ config_dir }}/{{ wgname }}.conf'
        create: yes
        state: present
        block: |
            [Interface]
            Address = {{ wg_ip }}/{{ wg_mask }}
            SaveConfig = true
            PrivateKey = {{ privatekey.stdout }}
            PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
            PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
            ListenPort = {{ listenPort }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ publickey.stdout }}"

    - name: Start wireguard for {{ wgname }}
      command: wg-quick up {{ wgname }}
      register: wireguardstart
      tags: wireguardrestart
    - debug:
        var: wireguardstart.stderr_lines
      tags: wireguardrestart
